### ISSUE TITLE
java.lang.IllegalStateException: mContentView is null 

### ISSUE THREAD

**Issue by unmagic** [canyinghao/CanRefresh#3]
java.lang.IllegalStateException: mContentView is null   at com.canyinghao.canrefresh.CanRefreshLayout.onFinishInflate(CanRefreshLayout.java:434)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:844)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394) Copy stack to clipboard

**Comment by unmagic** [comment]
找到这个问题的原因了，是没有引用can_content_view
